name: Trigger Target Workflow

on:
  workflow_dispatch:
    inputs:
      environment_version:
        description: 'Choose environment version (e.g., dev, sb, production)'
        required: true
        type: choice
        options:
          - dev
          - sb
          - production
      customer_company:
        description: 'Choose customer company (e.g., CLIPSPAY, OXPAY, FIDO)'
        required: true
        type: choice
        options:
          - CLIPSPAY
          - OXPAY
          - FIDO
  push:
    branches:
      - dev
      - sb

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment and customer company based on push branch
        if: github.event_name == 'push'
        run: |
          if [[ "${GITHUB_REF##*/}" == "dev" ]]; then
            echo "environment_version=dev" >> $GITHUB_ENV
            echo "customer_company=OXPAY" >> $GITHUB_ENV # Change this to the default company for dev branch
          elif [[ "${GITHUB_REF##*/}" == "sb" ]]; then
            echo "environment_version=sb" >> $GITHUB_ENV
            echo "customer_company=CLIPSPAY" >> $GITHUB_ENV # Change this to the default company for sb branch
          fi

      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="ballerine-io"
          repo_name="e2e-tests"
          event_type="trigger-workflow"
          environment_version="${{ github.event.inputs.environment_version || env.environment_version }}"
          customer_company="${{ github.event.inputs.customer_company || env.customer_company }}"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACTIONS_KEY }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"environment_version\": \"$environment_version\", \"customer_company\": \"$customer_company\"}}"
